### ISSUE TITLE
UnboundLocalError: local variable 'recorder' referenced before assignment

### ISSUE THREAD

**Issue by saxenam06** [PiggyMouth/MPC-CBF_for_ADS#1]
Hello, Thanks for open sourcing your work. I am facing an issue and unable to solve. Could you please help me. 
I am getting error when I run acc_with_cbf_mpc.py . Also the output of Scenario runner is mentioned below. Thank You.

python3 acc_with_cbf_mpc.py 
pygame 2.1.0 (SDL 2.0.16, Python 3.7.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
INFO: listening to server 192.168.10.243:2000

Welcome to CARLA manual control.

Use ARROWS or WASD keys for control.

    W            : throttle
    S            : brake
    AD           : steer
    Q            : toggle reverse
    Space        : hand-brake
    P            : toggle autopilot

    TAB          : change sensor position
    `            : next sensor
    [1-9]        : change to sensor [1-9]
    C            : change weather (Shift+C reverse)
    Backspace    : change vehicle

    R            : toggle recording images to disk

    F1           : toggle HUD
    H/?          : toggle help
    ESC          : quit

ERROR: local variable 'recorder' referenced before assignment
Traceback (most recent call last):
  File "acc_with_cbf_mpc.py", line 906, in game_loop
    world = World(client.get_world(), hud)
RuntimeError: time-out of 2000ms while waiting for the simulator, make sure the simulator is ready and connected to 192.168.10.243:2000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "acc_with_cbf_mpc.py", line 1136, in main
    game_loop(args)
  File "acc_with_cbf_mpc.py", line 1052, in game_loop
    recorder.end_recording()
UnboundLocalError: local variable 'recorder' referenced before assignment

Output of Scenario runner: 
python3 scenario_runner.py --scenario FollowLeadingVehicle_5 --reloadWorld --output
Preparing scenario: FollowLeadingVehicle_5
ScenarioManager: Running scenario FollowVehicle

 ======= Results of Scenario: FollowVehicle ---- TIMEOUT =======

 > Ego vehicles:
Actor(id=331, type=vehicle.lincoln.mkz2017); 

 > Other actors:
Actor(id=332, type=vehicle.nissan.patrol); 

 > Simulation Information
╒═════════════════════════════════╤═════════════════════╕
│ Start Time                      │ 2022-10-02 19:35:20 │
├─────────────────────────────────┼─────────────────────┤
│ End Time                        │ 2022-10-02 19:36:20 │
├─────────────────────────────────┼─────────────────────┤
│ Duration (System Time)          │ 60.23s              │
├─────────────────────────────────┼─────────────────────┤
│ Duration (Game Time)            │ 60.15s              │
├─────────────────────────────────┼─────────────────────┤
│ Ratio (System Time / Game Time) │ 0.999s              │
╘═════════════════════════════════╧═════════════════════╛

 > Criteria Information
╒══════════════════════════╤══════════════════════╤═════════╤══════════════╤════════════════╕
│ Actor                    │ Criterion            │ Result  │ Actual Value │ Expected Value │
├──────────────────────────┼──────────────────────┼─────────┼──────────────┼────────────────┤
│ lincoln.mkz2017 (id=331) │ CollisionTest (Req.) │ SUCCESS │ 0            │ 0              │
├──────────────────────────┼──────────────────────┼─────────┼──────────────┼────────────────┤
│                          │ Timeout (Req.)       │ FAILURE │ 60.15        │ 60             │
├──────────────────────────┼──────────────────────┼─────────┼──────────────┼────────────────┤
│                          │ GLOBAL RESULT        │ TIMEOUT │              │                │
╘══════════════════════════╧══════════════════════╧═════════╧══════════════╧════════════════╛
 ===============================================================

Not all scenario tests were successful
Destroying ego vehicle 331
ERROR: failed to destroy actor 331 : unable to destroy actor: not found 
No more scenarios .... Exiting

**Comment by PiggyMouth** [comment]
Hi, thank you for your interest in this work. Do you have the script `pygame_recorder.py` downloaded from the repository? Or can you try running the script after installing OpenCV using `pip install opencv-python`? If you still face problems in that script, you can comment out line 941, 963, and 1052 where this `recorder` variable is used, as it is only needed to record a video of your simulation.

Feel free to contact me again if you still face any problems.

**Comment by saxenam06** [comment]
Thank you so much for your response. Yes, by commenting the recorder Its working.
